namespace OH.DI.Web.ApiModels;

// ApiModel DTOs are used by ApiController classes and are typically kept in a side-by-side folder
public class DigitalCredentialDTO : CreateDigitalCredentialDTO
{
  public DigitalCredentialDTO(string id, string name, List<AssuredClaimDTO>? items = null) : base(name)
  {
    Id = id;
    Items = items ?? new List<AssuredClaimDTO>();
  }
  public string Id { get; set; }
  public List<AssuredClaimDTO> Items { get; set; }
}

// Creation DTOs should not include an ID if the ID will be generated by the back end
public abstract class CreateDigitalCredentialDTO
{
  protected CreateDigitalCredentialDTO(string name)
  {
    Name = name;
  }
  public string Name { get; set; }
}
